// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChriB8acRyO7jBFfliDNjkasaFjusvzVQ',
    appId: '1:774786152752:web:3fafc875d63727c47c70f5',
    messagingSenderId: '774786152752',
    projectId: 'buzz-app-eeb22',
    authDomain: 'buzz-app-eeb22.firebaseapp.com',
    storageBucket: 'buzz-app-eeb22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1tvrGsqZOD3CSzDwVGIPjWNSVTC1V3is',
    appId: '1:774786152752:android:250ab38be07f2da07c70f5',
    messagingSenderId: '774786152752',
    projectId: 'buzz-app-eeb22',
    storageBucket: 'buzz-app-eeb22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcf2MiT7BlDnK0PJ_1TlJpu_nNRtPGKA',
    appId: '1:774786152752:ios:c71f9c04d2a659287c70f5',
    messagingSenderId: '774786152752',
    projectId: 'buzz-app-eeb22',
    storageBucket: 'buzz-app-eeb22.firebasestorage.app',
    iosBundleId: 'com.example.buzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcf2MiT7BlDnK0PJ_1TlJpu_nNRtPGKA',
    appId: '1:774786152752:ios:c71f9c04d2a659287c70f5',
    messagingSenderId: '774786152752',
    projectId: 'buzz-app-eeb22',
    storageBucket: 'buzz-app-eeb22.firebasestorage.app',
    iosBundleId: 'com.example.buzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChriB8acRyO7jBFfliDNjkasaFjusvzVQ',
    appId: '1:774786152752:web:1cdbd68d69b1f3277c70f5',
    messagingSenderId: '774786152752',
    projectId: 'buzz-app-eeb22',
    authDomain: 'buzz-app-eeb22.firebaseapp.com',
    storageBucket: 'buzz-app-eeb22.firebasestorage.app',
  );
}
