// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSu4iqdJGrZootlrI-w3D_zVPU5ECrtY',
    appId: '1:409367514064:web:8e77967837a24c8722c7d5',
    messagingSenderId: '409367514064',
    projectId: 'buzz-notifications-9960f',
    authDomain: 'buzz-notifications-9960f.firebaseapp.com',
    storageBucket: 'buzz-notifications-9960f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrYZyy0ifrbjxW1_URwPXe3hY_Ca_gnQ',
    appId: '1:409367514064:android:a2ffabc45a183f7322c7d5',
    messagingSenderId: '409367514064',
    projectId: 'buzz-notifications-9960f',
    storageBucket: 'buzz-notifications-9960f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nHLE76RjBf6BGGFQGmvpfPQIISAjZ-Q',
    appId: '1:409367514064:ios:e1a3c20819f8ee5822c7d5',
    messagingSenderId: '409367514064',
    projectId: 'buzz-notifications-9960f',
    storageBucket: 'buzz-notifications-9960f.firebasestorage.app',
    iosBundleId: 'com.example.buzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nHLE76RjBf6BGGFQGmvpfPQIISAjZ-Q',
    appId: '1:409367514064:ios:e1a3c20819f8ee5822c7d5',
    messagingSenderId: '409367514064',
    projectId: 'buzz-notifications-9960f',
    storageBucket: 'buzz-notifications-9960f.firebasestorage.app',
    iosBundleId: 'com.example.buzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoSu4iqdJGrZootlrI-w3D_zVPU5ECrtY',
    appId: '1:409367514064:web:6fbafb035c35ee1b22c7d5',
    messagingSenderId: '409367514064',
    projectId: 'buzz-notifications-9960f',
    authDomain: 'buzz-notifications-9960f.firebaseapp.com',
    storageBucket: 'buzz-notifications-9960f.firebasestorage.app',
  );
}
